[settings]
app_name = "My Streamlit App"
version = "0.1.0"
debug = true

[database]
url = "sqlite:///my_database.db"

[api]
key = "your_api_key_here"
endpoint = "https://api.example.com"

[logging]
level = "INFO"
file = "app.log"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false