[settings]
app_name = "COSMED Data Converter Web Version"
version = "0.1.0"

[server]
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false
